### ISSUE TITLE
Telephone number is optional

### ISSUE THREAD

**Issue by BerendWouters** [Brixel/HaSpMan#104]
**Describe the bug**
The official registration form (paper version) states the telephone number is optional. The digital form requires it.

**To Reproduce**
1. Go to 'New member'
2. Enter an e-mailaddress 'Telephone number'
3. Don't enter a telephone number

**Expected behavior**
The validation error isn't triggered

**Screenshots**
![image](https://user-images.githubusercontent.com/18244097/218831930-bbc92f3e-b4c3-4f16-9c06-f100668eddd1.png)

**Comment by vyruz1986** [comment]
Either email or phone number should be required, supplying both is optional.

Weird, this did work in the past, and the conditional validation attributes are still is present in the form model: https://github.com/Brixel/HaSpMan/blob/master/Web/Models/MemberForm.cs#L17-L24

I also can't see where the 'The PhoneNumber field is required' message comes from...
