### ISSUE TITLE
Unable to create a membership fee transaction

### ISSUE THREAD

**Issue by Kenny-Lacroix** [Brixel/HaSpMan#150]
**Describe the bug**
Unable to create a transaction from the type membership fee. it results in 

**To Reproduce**
1. Go to New Transaction
2. Fill in the required fields
3. Submit
4. See following screen
![image](https://github.com/Brixel/HaSpMan/assets/62295602/9bc00090-6147-45c4-b3bc-0d39015c149e)

**Expected behavior**
To be able to create a transaction

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version ???

**Priority**
If possible, assign a milestone to the feature request. This indicates priority. The milestones follow the [semver](https://semver.org) rules: in short, 1.0.1 is a higher priority than 1.1.0

**Comment by BerendWouters** [comment]
This is due to Microsoft still feeling the urge to apply claims transformations (https://github.com/dotnet/aspnetcore/issues/4660)
