### ISSUE TITLE
I can create the exact same user multiple times

### ISSUE THREAD

**Issue by Kenny-Lacroix** [Brixel/HaSpMan#155]
**Describe the bug**
After some testing i accidentily created the same user twice because i didn't have a precise way of knowing the user already existed.

**Expected behavior**
Get an error that says this user already exists

**Priority**
If possible, assign a milestone to the feature request. This indicates priority. The milestones follow the [semver](https://semver.org) rules: in short, 1.0.1 is a higher priority than 1.1.0

**Comment by vyruz1986** [comment]
Agree this needs to be fixed, but what makes a member unique? Combination of name/address?

**Comment by vyruz1986** [comment]
By lack of feedback, I winged it and created a solution in #162 which prevent either adding new members, or changing existing ones, if the end result is either the following 2 scenarios:
- Member has an email which is already defined for another member
- Member has exactly the same firstname, lastname, street, house number, zipcode, city and country as another member
