### ISSUE TITLE
App crashes when manualy changing memberfee experation date

### ISSUE THREAD

**Issue by Kenny-Lacroix** [Brixel/HaSpMan#158]
**Describe the bug**
When making a new member fee transaction, if you want to manually change the experation date the app crashes.

**To Reproduce**
1. Go to new transaction
2. Fill in the form to extend the membership status from a member
3. click on the new experation month date pîcker
4. See the crash

**Expected behavior**
when clicking on the date picker, see the month and be able to select a date

**Screenshots**
![image](https://github.com/Brixel/HaSpMan/assets/62295602/fa3f94fe-e308-4e81-bf62-2d6a801093a8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version /

**Comment by BerendWouters** [comment]
Fixed with #161
