### ISSUE TITLE
New members: Phone number is required field

### ISSUE THREAD

**Issue by kefcom** [Brixel/HaSpMan#27]
Phone number is a required field, yet we don't explicitly require new members to provide a phone number.

**Comment by vyruz1986** [comment]
There is a requirement that we have either a valid email address or phone number, both are optional, but at least of them is required.  Currently there's a simple `[Required]` annotation on both these properties in the member form model. This will have to be updated to a more complex validator that checks the combination of email/phone

**Comment by BerendWouters** [comment]
Long live complex validations.
