### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by kefcom** [Brixel/HaSpMan#34]
If possible I'd like to see the date formatted as dd/mm/yyyy or yyyy/mm/dd.

**Comment by BerendWouters** [comment]
Looks like all dates a formatted as dd/mm/yyyy already. Could you confirm @kefcom ?

**Comment by BerendWouters** [comment]
*bump* @kefcom

**Comment by kefcom** [comment]
Looks fixed, thanks!

**Comment by kefcom** [comment]
It seems I missed this one :) In the transactions list it still shows up in the wrong format:
![afbeelding](https://user-images.githubusercontent.com/6786386/178200502-959f7c22-9e16-43dd-8b04-f2acfaf16891.png)

**Comment by kefcom** [comment]
Datepicker is fixed/improved on the add member page, but not on the add transaction page.

**Comment by kefcom** [comment]
Found another bad date on the new transaction page:
![afbeelding](https://user-images.githubusercontent.com/6786386/185482972-1f18a51b-25c7-41cc-a33b-f37ac359b55d.png)
