### ISSUE TITLE
transaction fields not updating properly

### ISSUE THREAD

**Issue by kefcom** [Brixel/HaSpMan#37]
Eg: when booking a credit (donation)
![afbeelding](https://user-images.githubusercontent.com/6786386/144809002-97caefd0-e9ef-4f00-95b5-03463f399adf.png)
then switching to debit, it doesn't update:
![afbeelding](https://user-images.githubusercontent.com/6786386/144809225-45432f38-7a6f-4560-baa9-f626fa1ad8f0.png)
however when booking the transaction it shows
![afbeelding](https://user-images.githubusercontent.com/6786386/144809341-970d5e47-a026-4cc1-b1ff-07bb7b742b38.png)
which makes me think I booked a donation as debit? Yet when editing the transaction it shows it is in fact a credit ¯\_(ツ)_/¯

**Comment by Joren-Thijs** [comment]
@vyruz1986 has a fix for this.

**Comment by kefcom** [comment]
This problem just got more weird. When creating a new transaction the type is set to 'DebitWorkshopFee'
![afbeelding](https://user-images.githubusercontent.com/6786386/185471536-5f7a2aac-790f-4eec-b76c-0a72660c0862.png)

**Comment by BerendWouters** [comment]
This seems to be fixed?
![image](https://user-images.githubusercontent.com/18244097/188272204-402e758f-14cd-4d5f-b3bf-df6f2b40658e.png)
