### ISSUE TITLE
Improve visibility of In and Out in the transaction overview

### ISSUE THREAD

**Issue by kefcom** [Brixel/HaSpMan#64]
It would be nice to have a better view of what's going In and Out in the transaction overview. My suggestion would be to color the rows of IN's green, and the OUT's red, with a '+' and '-' before the transaction ammount.

![afbeelding](https://user-images.githubusercontent.com/6786386/183241817-72387ee6-f513-4fd1-8e61-53326c75f341.png)

**Comment by BerendWouters** [comment]
Isn't the "Received" column a bit oddly named? Transaction date would be better, I guess?

**Comment by kefcom** [comment]
Yes, transaction date is better.
