### ISSUE TITLE
Total of all transactions per bank

### ISSUE THREAD

**Issue by kefcom** [Brixel/HaSpMan#78]
Just like in Malman, I would like to see a total of all debit/credit transactions on any given bank account. This value is used to check if all transactions are booked and should at all times match the amount of money on the bank.

![afbeelding](https://user-images.githubusercontent.com/6786386/185470469-7052b735-7d64-475c-822e-39c0270f5686.png)

**Comment by BerendWouters** [comment]
To compare the current amount on the bank with the actual bank account, we should also be able to set the "initial" state of the HaSpMan bank account to the value before using HaSpMan.

**Comment by BerendWouters** [comment]
When I try to edit a bank account, the page crashes.
