### ISSUE TITLE
Date of Birth field for users

### ISSUE THREAD

**Issue by kefcom** [Brixel/HaSpMan#97]
It seems we don't keep a record of the date of birth of our users like we used to do in malman. Please provide a field.

**Comment by BerendWouters** [comment]
Do we 'need' this? What's the added benefit of knowing someone's birthdate?

**Comment by kefcom** [comment]
Would be nice to get an average age of the members. Other then that I don't really know the benefit.

**Comment by Kenny-Lacroix** [comment]
We don't have a need to store this data
